# This file was generated by GoReleaser. DO NOT EDIT.
cask "vpd" do
  name "vpd"
  desc "Vojtech Pastyrik Utils"
  homepage "https://github.com/VojtechPastyrik/vpd"
  version "1.3.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "vpd"

  on_macos do
    url "https://github.com/VojtechPastyrik/vpd/releases/download/v#{version}/vpd_#{version}_darwin_all.tar.gz"
    sha256 "31428a24721da5bc49fea49f91ffffe6301c7e51a178da0fd7e64bfe22096bb8"
  end

  on_linux do
    on_intel do
      url "https://github.com/VojtechPastyrik/vpd/releases/download/v#{version}/vpd_#{version}_linux_amd64.tar.gz"
      sha256 "e73e0b889f697498f71ac6062bc52de55954aad2a3c7d1dacb206083442b275a"
    end
    on_arm do
      url "https://github.com/VojtechPastyrik/vpd/releases/download/v#{version}/vpd_#{version}_linux_arm64.tar.gz"
      sha256 "5baa3b41748a10bf2304e2be3069d26ca88ef547bd9af21dc63a82c6cae838da"
    end
  end

  caveats do
    "How to use this binary: https://github.com/VojtechPastyrik/vpd"
  end

  # No zap stanza required
end
