# This file was generated by GoReleaser. DO NOT EDIT.
cask "vpd" do
  name "vpd"
  desc "Vojtech Pastyrik Utils"
  homepage "https://github.com/VojtechPastyrik/vpd"
  version "1.2.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "vpd"

  on_macos do
    url "https://github.com/VojtechPastyrik/vpd/releases/download/v#{version}/vpd_#{version}_darwin_all.tar.gz"
    sha256 "9fb5542f07c8f6211f5c4ee56b32df1c8be76adc1bb1ce1def6483de5f0624c2"
  end

  on_linux do
    on_intel do
      url "https://github.com/VojtechPastyrik/vpd/releases/download/v#{version}/vpd_#{version}_linux_amd64.tar.gz"
      sha256 "c714c9ac1bd3fc26ad62c13903ff873d09ca2cb88df9dd2ef6faaa627357a81c"
    end
    on_arm do
      url "https://github.com/VojtechPastyrik/vpd/releases/download/v#{version}/vpd_#{version}_linux_arm64.tar.gz"
      sha256 "6c09a41f02179cf810f7f94b1b256ef5c6604ff084a097524c1b6ede8e3ea1b7"
    end
  end

  caveats do
    "How to use this binary: https://github.com/VojtechPastyrik/vpd"
  end

  # No zap stanza required
end
