# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class VpUtils < Formula
  desc "Vojtech Pastyrik Utils"
  homepage "https://github.com/VojtechPastyrik/vp-utils"
  version "0.11.1"

  on_macos do
    url "https://github.com/VojtechPastyrik/vp-utils/releases/download/v0.11.1/vp-utils_0.11.1_darwin_all.tar.gz"
    sha256 "73b1224b43d60d3d5adc024b1b5644a174b6049d698039aa7c2a4648733f4911"

    def install
      bin.install "vp-utils"
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/VojtechPastyrik/vp-utils/releases/download/v0.11.1/vp-utils_0.11.1_linux_amd64.tar.gz"
      sha256 "a09efb18e436a1e14b067ffb36733fecadf0c40b60946732b3fcf3f0ed4a2d48"
      def install
        bin.install "vp-utils"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/VojtechPastyrik/vp-utils/releases/download/v0.11.1/vp-utils_0.11.1_linux_arm64.tar.gz"
      sha256 "96311a5e2c21cae0460494f6c7f9732f987b33d6b0743d05d2ecc3f22f05560a"
      def install
        bin.install "vp-utils"
      end
    end
  end

  def caveats
    <<~EOS
      How to use this binary: https://github.com/VojtechPastyrik/vp-utils
    EOS
  end

  test do
    system "#{bin}/vp-utils version"
  end
end
