# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Vpd < Formula
  desc "Vojtech Pastyrik Utils"
  homepage "https://github.com/VojtechPastyrik/vpd"
  version "1.1.0"

  on_macos do
    url "https://github.com/VojtechPastyrik/vpd/releases/download/v1.1.0/vpd_1.1.0_darwin_all.tar.gz"
    sha256 "317d471276bf322b8e1a399db3348c004564d9c75b47d67b458a4f095044c84e"

    def install
      bin.install "vpd"
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/VojtechPastyrik/vpd/releases/download/v1.1.0/vpd_1.1.0_linux_amd64.tar.gz"
      sha256 "72b86600af74cab8b5a5f29a99599c3efdcca36b43521a0f2f1aef54450a5fdc"
      def install
        bin.install "vpd"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/VojtechPastyrik/vpd/releases/download/v1.1.0/vpd_1.1.0_linux_arm64.tar.gz"
      sha256 "6fdc3041169099e23c9b7f91ddba0b9f22cba9e257f738e64ae1121171dc51e2"
      def install
        bin.install "vpd"
      end
    end
  end

  def caveats
    <<~EOS
      How to use this binary: https://github.com/VojtechPastyrik/vpd
    EOS
  end

  test do
    system "#{bin}/vpd version"
  end
end
