# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Vpd < Formula
  desc "Vojtech Pastyrik Utils"
  homepage "https://github.com/VojtechPastyrik/vpd"
  version "1.4.0"
  license "MIT"

  on_macos do
    url "https://github.com/VojtechPastyrik/vpd/releases/download/v1.4.0/vpd_1.4.0_darwin_all.tar.gz"
    sha256 "ea019291c4c9ed51e85dcad4b8f8a3c6a06f5d6fdf3620b7d6590f29efcaf4ef"

    define_method(:install) do
      bin.install "vpd"
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/VojtechPastyrik/vpd/releases/download/v1.4.0/vpd_1.4.0_linux_amd64.tar.gz"
      sha256 "da6709256f2fbdf570d169ab710e7e57f8715288f16286bd5fcf3620e7534023"
      define_method(:install) do
        bin.install "vpd"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/VojtechPastyrik/vpd/releases/download/v1.4.0/vpd_1.4.0_linux_arm64.tar.gz"
      sha256 "dad795f8650ef2eabae3ad01e0406e2eb93dd202215a8877dad15946d488b768"
      define_method(:install) do
        bin.install "vpd"
      end
    end
  end
end
